In [2]:
import numpy as np


In [3]:
np

<module 'numpy' from '/home/dima/.local/lib/python3.10/site-packages/numpy/__init__.py'>

In [6]:
arr=np.array([1,2,3,4])
arr

array([1, 2, 3, 4])

In [7]:
arr=np.array((1,2,3,4))
arr

array([1, 2, 3, 4])

In [8]:
type(arr)

numpy.ndarray

In [10]:
arr[0]

np.int64(1)

In [11]:
arr[-1]

np.int64(4)

In [12]:
arr.shape

(4,)

In [13]:
arr.ndim

1

In [14]:
arr.size

4

In [15]:
arr.dtype

dtype('int64')

In [16]:
arr.itemsize

8

In [21]:
sarr = np.array([True,10,'abc', 5.5])
sarr

array(['True', '10', 'abc', '5.5'], dtype='<U32')

In [22]:
sarr.dtype.name

'str1024'

In [23]:
sarr.itemsize

128

In [24]:
obj_arr=np.array([{'city':'London'},{'city':'Moscow'}])
obj_arr

array([{'city': 'London'}, {'city': 'Moscow'}], dtype=object)

In [25]:
obj_arr.dtype.name

'object'

In [26]:
obj_arr.itemsize

8

### Two dimensions arrays

In [29]:
first = np.array([[1,2,3], [4,5,6]])
first

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
first.shape

(2, 3)

In [31]:

first.ndim

2

In [33]:
second = np.array([[1,1,1],[0,0,0]])
second

array([[1, 1, 1],
       [0, 0, 0]])

In [34]:
second.shape

(2, 3)

In [35]:
first+second

array([[2, 3, 4],
       [4, 5, 6]])

In [36]:
first * second

array([[1, 2, 3],
       [0, 0, 0]])

In [38]:
first * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [39]:
first

array([[1, 2, 3],
       [4, 5, 6]])

In [42]:
first[1,2]

np.int64(6)

In [44]:
first[1][2]

np.int64(6)

In [46]:
np.concatenate((first, second))

array([[1, 2, 3],
       [4, 5, 6],
       [1, 1, 1],
       [0, 0, 0]])

In [48]:
np.concatenate((second,first))

array([[1, 1, 1],
       [0, 0, 0],
       [1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate((second,first), axis=1)

array([[1, 1, 1, 1, 2, 3],
       [0, 0, 0, 4, 5, 6]])

In [50]:
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8])))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
np.concatenate((np.array([1,2,3,4]), np.array([5,6,7,8])),axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

### Random in Numpy

In [52]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [53]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [55]:
np.zeros((3,4), dtype='int')

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [56]:
np.zeros((3,4), dtype=str)

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

In [57]:
np.ones((3,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [58]:
np.ones((3,4), dtype='str')

array([['1', '1', '1', '1'],
       ['1', '1', '1', '1'],
       ['1', '1', '1', '1']], dtype='<U1')

In [66]:
np.random.random([2,3])

array([[0.84656149, 0.07964548, 0.50524609],
       [0.0652865 , 0.42812233, 0.09653092]])

In [67]:
np.random.random((2,3))

array([[0.12715997, 0.59674531, 0.226012  ],
       [0.10694568, 0.22030621, 0.34982629]])

In [68]:
np.random.seed(2)
np.random.random([2,3])

array([[0.4359949 , 0.02592623, 0.54966248],
       [0.43532239, 0.4203678 , 0.33033482]])

In [69]:
np.random.randint(10,20,size=[2,3])

array([[15, 14, 14],
       [15, 17, 13]])

In [70]:
np.random.uniform(size=(3,4))

array([[0.49856117, 0.58679698, 0.71975423, 0.25849809],
       [0.54620732, 0.40730783, 0.17698462, 0.96963241],
       [0.29701836, 0.28786882, 0.11619332, 0.18172704]])

In [72]:
np.random.uniform(1,2,size=(3,4)).round(2)

array([[1.99, 1.12, 1.15, 1.85],
       [1.51, 1.22, 1.99, 1.32],
       [1.26, 1.81, 1.35, 1.47]])

In [73]:
np.random.choice(np.array([1,2,3]),size=20)

array([2, 3, 3, 3, 1, 3, 2, 1, 1, 2, 2, 3, 2, 2, 2, 2, 3, 1, 3, 3])

In [74]:
np.random.choice(np.array([1,2,3]),size=[2,3])

array([[1, 2, 3],
       [1, 3, 1]])

In [76]:
np.random.choice(np.array(['a','b','c']),size=10)

array(['a', 'c', 'b', 'a', 'a', 'c', 'c', 'b', 'b', 'b'], dtype='<U1')

### Arange and Reshape

In [77]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
type(np.arange(10))

numpy.ndarray

In [80]:
np.arange(15,25)

array([15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [81]:
np.arange(20,30,3)

array([20, 23, 26, 29])

In [82]:
np.arange(-15,5,4)

array([-15, -11,  -7,  -3,   1])

In [83]:
np.arange(start=10, stop=20,step=5)

array([10, 15])

In [84]:
np.arange(20).reshape(2,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [86]:
np.arange(20).reshape([3,10])

ValueError: cannot reshape array of size 20 into shape (3,10)

In [87]:
np.arange(20).reshape(2,10).reshape([4,5])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [88]:
np.random.random(10,)

array([0.55097791, 0.97291069, 0.11277622, 0.31325853, 0.04179771,
       0.73839976, 0.65751239, 0.21463575, 0.41675344, 0.64384193])

In [90]:
np.random.random(10,).reshape((2,5))

array([[0.91845865, 0.59208458, 0.34623791, 0.26377853, 0.91391548],
       [0.41973546, 0.54019152, 0.60844216, 0.82624983, 0.62356318]])

In [92]:
np.random.seed(10)
np.random.randint(50,80, (4,3,3))

array([[[59, 79, 54],
        [65, 50, 67],
        [77, 78, 75]],

       [[79, 66, 79],
        [67, 76, 58],
        [59, 50, 60]],

       [[58, 72, 54],
        [69, 66, 54],
        [65, 61, 72]],

       [[74, 61, 76],
        [51, 58, 54],
        [64, 67, 69]]])

In [93]:
np.random.seed(10)
np.random.randint(50,80, (4,3,3)).flatten()

array([59, 79, 54, 65, 50, 67, 77, 78, 75, 79, 66, 79, 67, 76, 58, 59, 50,
       60, 58, 72, 54, 69, 66, 54, 65, 61, 72, 74, 61, 76, 51, 58, 54, 64,
       67, 69])

In [97]:
np.arange(10).reshape(2,5).flatten()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Real life examples

#### Ex.1

In [102]:
prices = np.random.uniform(10,100,5).round(2)
prices

array([84.88, 37.88, 63.78, 88.52, 98.47])

In [104]:
quantities = np.random.randint(1,20,5)
quantities

array([14, 16,  7, 11, 12])

In [109]:
income = prices*quantities
income

array([1188.32,  606.08,  446.46,  973.72, 1181.64])

In [110]:
income.sum().round(2)

np.float64(4396.22)

In [113]:
total=np.sum(income).round(2)
total

np.float64(4396.22)

#### Ex.2

In [115]:
views = np.random.randint(500,1000,5)
views

array([685, 997, 579, 864, 732])

In [117]:
max_views=np.max(views)
max_views

np.int64(997)

In [118]:
min_views = min(views)
min_views

np.int64(579)

In [122]:
avg_views = np.mean(views).round(2)
avg_views

np.float64(771.4)

In [123]:
total = np.sum(views)
total

np.int64(3857)

#### Ex.3

In [129]:
order_id = np.arange(1001,1009)
order_id

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008])

In [134]:
batches = np.split(order_id,2)
batches

[array([1001, 1002, 1003, 1004]), array([1005, 1006, 1007, 1008])]

In [135]:
for batch in batches:
    print("First element in the batch",batch[0])
    print("First element in the batch",batch[1])

First element in the batch 1001
First element in the batch 1002
First element in the batch 1005
First element in the batch 1006


In [139]:
for i, batch in enumerate(batches):
    print(f"Batch number {i}:")
    print("First element in the batch",batch[0])
    print("First element in the batch",batch[1])
    print('')

Batch number 0:
First element in the batch 1001
First element in the batch 1002

Batch number 1:
First element in the batch 1005
First element in the batch 1006



#### Ex.4

In [143]:
ratings = np.random.uniform(1,5,8).round(1)
ratings

array([1.2, 4.5, 4.1, 4.5, 2.7, 3.4, 3.1, 3.4])

In [145]:
positive_ratings = ratings[ratings > 4.0]
positive_ratings

array([4.5, 4.1, 4.5])

In [146]:
negative_ratings = ratings[ratings < 4.0]
negative_ratings

array([1.2, 2.7, 3.4, 3.1, 3.4])

#### Ex.5

In [149]:
order_num = np.array([[1,5,3,7],[6,8,12,21]])
order_num

array([[ 1,  5,  3,  7],
       [ 6,  8, 12, 21]])

In [151]:
total_quantities=np.sum(order_num, axis=0)
total_quantities

array([ 7, 13, 15, 28])

In [152]:
total_quantities=np.sum(order_num, axis=1)
total_quantities

array([16, 47])

In [154]:
avg_quantities = np.mean(order_num, axis=0).round(2)
avg_quantities

array([ 3.5,  6.5,  7.5, 14. ])

#### Ex.6

In [158]:
pr_raiting = np.random.uniform(1,5,12).round(1).reshape(3,4)
pr_raiting

array([[3.6, 2.4, 1.3, 1.9],
       [1.5, 4. , 2.4, 3.3],
       [1.7, 1.2, 4.3, 4.2]])

In [161]:
avg_raiting_per_category=np.mean(pr_raiting,axis=0).round(2)
avg_raiting_per_category

array([2.27, 2.53, 2.67, 3.13])

In [163]:
# max raiting in each category
max_raiting = np.max(pr_raiting, axis=0)
max_raiting

array([3.6, 4. , 4.3, 4.2])

#### Ex.7

In [164]:
comp = ['Google','Microsoft','Apple']
days = ['Mon 1 April', 'Tue 2 April']
price_types = ['Open','Close','Hight','Low']

In [166]:
# shape will be (3,2,4)
np.random.seed(1)
stock_prices =np.round(np.random.random((len(comp),len(days), len(price_types))),2)
stock_prices

array([[[0.42, 0.72, 0.  , 0.3 ],
        [0.15, 0.09, 0.19, 0.35]],

       [[0.4 , 0.54, 0.42, 0.69],
        [0.2 , 0.88, 0.03, 0.67]],

       [[0.42, 0.56, 0.14, 0.2 ],
        [0.8 , 0.97, 0.31, 0.69]]])

In [169]:
for indx_axis_0, company in enumerate(comp):
    print(f'Stock prices for the {company}:')
    for indx_axis_1, day in enumerate(days):
        print(f'Day: {day}')
        for indx_axis_2, price_type in enumerate(price_types):
            print(f'{price_type} Price: {stock_prices[indx_axis_0,indx_axis_1,indx_axis_2]}')
        print('')
    print('')

Stock prices for the Google:
Day: Mon 1 April
Open Price: 0.42
Close Price: 0.72
Hight Price: 0.0
Low Price: 0.3

Day: Tue 2 April
Open Price: 0.15
Close Price: 0.09
Hight Price: 0.19
Low Price: 0.35


Stock prices for the Microsoft:
Day: Mon 1 April
Open Price: 0.4
Close Price: 0.54
Hight Price: 0.42
Low Price: 0.69

Day: Tue 2 April
Open Price: 0.2
Close Price: 0.88
Hight Price: 0.03
Low Price: 0.67


Stock prices for the Apple:
Day: Mon 1 April
Open Price: 0.42
Close Price: 0.56
Hight Price: 0.14
Low Price: 0.2

Day: Tue 2 April
Open Price: 0.8
Close Price: 0.97
Hight Price: 0.31
Low Price: 0.69


